// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgJce-FrEavskjkOv2K6XnhWN8aidr1Ws',
    appId: '1:649629137179:web:b3162eed10249515053bbe',
    messagingSenderId: '649629137179',
    projectId: 'medica-719b5',
    authDomain: 'medica-719b5.firebaseapp.com',
    storageBucket: 'medica-719b5.appspot.com',
    measurementId: 'G-GFF2N0BESG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMPrsE5qZk0nMiOSEnh9RsKA5Rrzvh618',
    appId: '1:649629137179:ios:a868b9600863cb97053bbe',
    messagingSenderId: '649629137179',
    projectId: 'medica-719b5',
    storageBucket: 'medica-719b5.appspot.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgJce-FrEavskjkOv2K6XnhWN8aidr1Ws',
    appId: '1:649629137179:web:feb5c4985ac6f6b8053bbe',
    messagingSenderId: '649629137179',
    projectId: 'medica-719b5',
    authDomain: 'medica-719b5.firebaseapp.com',
    storageBucket: 'medica-719b5.appspot.com',
    measurementId: 'G-MYS2RHRCG0',
  );
}
